apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
spec:
  containers:
  - name: app
    image: busybox
    command: [ "sh", "-c", "sleep 3600" ]
    volumeMounts:
    - name: hostdata
      mountPath: /host-data
  volumes:
  - name: hostdata
    hostPath:
      path: /tmp/hostpath-example
      type: DirectoryOrCreate
