# Basic ServiceAccount (Kubernetes 1.24+: uses projected volume tokens)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp-serviceaccount
  namespace: default
  labels:
    app: webapp
    component: auth
  annotations:
    description: "ServiceAccount for webapp pods"
automountServiceAccountToken: true # Default: true, uses projected volumes (auto-rotating tokens)
---
# ServiceAccount with disabled token mounting
apiVersion: v1
kind: ServiceAccount
metadata:
  name: no-token-sa
  namespace: default
automountServiceAccountToken: false # Disables automatic token mounting
---
# ServiceAccount with image pull secrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-sa
  namespace: default
imagePullSecrets:
- name: regcred # Docker registry secret for private images
- name: another-registry-secret
automountServiceAccountToken: true
---
# ServiceAccount with additional secrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-with-secrets-sa
  namespace: default
secrets:
- name: app-secret # Additional secret mounted to pods using this SA
- name: tls-secret
automountServiceAccountToken: true
