apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  labels:
    app: nginx
    type: nodeport
spec:
  type: NodePort

  # Selector must match pod labels
  selector:
    app: nginx
    tier: frontend

  ports:
  - name: http
    port: 80 # Port exposed by the service (cluster internal)
    targetPort: 8080 # Port on the pod container
    nodePort: 30080 # Port exposed on each node (30000-32767)
    protocol: TCP
  # If nodePort is omitted, Kubernetes auto-assigns one in range 30000-32767
  # Example without specifying nodePort:
  # - name: auto-port
  #   port: 80
  #   targetPort: 8080    # If omitted, defaults to port value (80)

---
# Example deployment that this service will route to
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  template:
    metadata:
      labels:
        app: nginx # Must match service selector
        tier: frontend # Must match service selector
    spec:
      containers:
      - name: nginx
        image: nginx:1.20
        ports:
        - containerPort: 8080 # Must match service targetPort

# Key Points:
# - port: 80 = Service port (internal cluster access)
# - targetPort: 8080 = Pod container port
# - nodePort: 30080 = External port on each node
# - Access externally: http://<node-ip>:30080
# - Access internally: http://nginx-nodeport:80
# - NodePort range: 30000-32767
# - If nodePort omitted, auto-assigned from available range
# - If targetPort omitted, defaults to port value
